---
- name: "Setting up JupyterLab Elyra globally"
  hosts: localhost
  become: true
  become_user: root
  tasks:
    - name: Update packages
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Fix broken dependencies and upgrade packages
      apt:
        upgrade: dist
        force_apt_get: yes

    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present

    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Upgrade pip to latest
      ansible.builtin.pip:
        name: pip
        state: latest
        executable: pip3

    - name: Install Elyra globally
      ansible.builtin.pip:
        name: elyra
        executable: pip3

    - name: Restart JupyterHub service
      systemd:
        name: jupyterhub
        state: restarted
